Repository citusdata/citus_docs, pull requests merged in 2018-07, with the labels that each got.

#692 Motivate choosing dist column
  sharding/data_modeling.rst
Labels: needs review

#697 add mark_tables_colocated in reference section
  develop/api_udf.rst
  develop/reference_ddl.rst
Labels: needs review

#698 When not to use citus -- match website suggestions
  get_started/what_is_citus.rst
Labels: needs review

#701 Add timeseries tips to data modeling section
  faq/faq.rst
  sharding/data_modeling.rst
Labels: needs review

#699 Motivate citus in intro
  _static/css/citus.css
  get_started/concepts.rst
  get_started/what_is_citus.rst
Labels: needs review

#703 Bump Citus version to 7.4.1
  installation/multi_machine_aws.rst
Labels: needs review

#718 get_rebalance_progress
  cloud/performance.rst
  develop/api_udf.rst
Labels: needs review

#707 New features from django-multitenant 1.10
  develop/migration_mt_django.rst
Labels: needs review

#682 Menu options collapsed by default
  articles/index.rst
  index.rst
Labels: needs review

#656 Document TopN
  develop/reference_sql.rst
Labels: needs review

#714 New citus directly supports HLL aggregates
  develop/reference_sql.rst
  use_cases/realtime_analytics.rst
Labels: needs review

#715 Select for update
  develop/reference_dml.rst
Labels: needs review

#721 More of our extensions
  admin_guide/cluster_management.rst
Labels: needs review

#704 Work ref table fks into the conversation
  develop/api_udf.rst
  develop/reference_ddl.rst
Labels: needs review

#700 Add some diagrams for choosing app type
  develop/app_type.rst
Labels: needs review

#709 Document new connection GUC/table
  admin_guide/cluster_management.rst
  develop/api_guc.rst
  develop/api_metadata.rst
Labels: in progress

#708 Note misleading error for table non-owners
  reference/common_errors.rst
Labels: 5day, in progress

#723 Fixing small typos and query inconsistencies
  admin_guide/diagnostic_queries.rst
  cloud/availability.rst
  develop/api_guc.rst
  develop/api_metadata.rst
  develop/api_udf.rst
  develop/append.rst
  develop/migration_mt_query.rst
  develop/migration_mt_schema.rst
  develop/reference_ddl.rst
  develop/reference_sql.rst
  performance/performance_tuning.rst
  sharding/data_modeling.rst
  use_cases/multi_tenant.rst
  use_cases/timeseries.rst
Labels: needs review

#720 Mention unlogged table for scaling ingestion
  performance/performance_tuning.rst
Labels: needs review

#728 RLS section and example
  admin_guide/table_management.rst
  cloud/security.rst
Labels: needs review

#731 Release 7.5
  admin_guide/upgrading_citus.rst
  cloud/additional_extensions.rst
  conf.py
  develop/api_guc.rst
  develop/api_metadata.rst
  index.rst
  installation/multi_machine_aws.rst
  installation/multi_machine_debian.rst
  installation/multi_machine_rhel.rst
  installation/single_machine_debian.rst
  installation/single_machine_rhel.rst
Labels: needs review

#727 Citus stat statements
  admin_guide/cluster_management.rst
  develop/api_metadata.rst
  develop/api_udf.rst
Labels: needs review
