Repository citusdata/citus_docs, pull requests merged in 2018-11, with the labels that each got.

#800 New views etc in 8.0
  arch/mx.rst
  cloud/additional.rst
  develop/api_guc.rst
  develop/api_metadata.rst
  develop/reference_ddl.rst
  get_started/concepts.rst
  index.rst
  performance/performance_tuning.rst
Labels: needs review

#810 Onder's suggestions about MX
  arch/mx.rst
  develop/api_guc.rst
  develop/api_metadata.rst
Labels: needs review

#802 Preparing for 8.0
  admin_guide/upgrading_citus.rst
  cloud/additional_extensions.rst
  conf.py
  develop/migration_rt.rst
  extra/enterprise.rst
  index.rst
  installation/multi_machine_aws.rst
  installation/multi_machine_debian.rst
  installation/multi_machine_rhel.rst
  installation/single_machine_debian.rst
  installation/single_machine_rhel.rst
  reference/common_errors.rst
Labels: needs review

#813 Warn not to use docker for prod
  installation/single_machine_docker.rst
Labels: needs review

#796 Simplify "What is citus" section
  get_started/what_is_citus.rst
Labels: needs review

#803 fix broken sphinx install link
  README.md
Labels: approved

#819 More AZs supported in Cloud
  cloud/getting_started.rst
Labels: needs review

#815 Update package versions to match those currently on Cloud
  cloud/additional_extensions.rst
Labels: 5day, needs review

#820 Update SQL support section
  develop/reference_workarounds.rst
Labels: needs review
