Repository citusdata/citus_docs, pull requests merged in 2018-02, with the labels that each got.

#605 Bump Citus to 7.2.1
  installation/multi_machine_aws.rst
Labels: needs review

#486 Reflect that 2PC is now the default
  dist_tables/ddl.rst
  reference/configuration.rst
Labels: ready

#615 Add documentation on reference tables being partmethod "n"
  reference/metadata_tables.rst
Labels: needs review

#618 Use %s rather than %I
  extra/query_propagation.rst
Labels: in progress
